// <auto-generated />
using System;
using EntityLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityLib.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    partial class ApplicationDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLib.CuisineManagment.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ParentCuisineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCuisineId");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("EntityLib.LocationManagment.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProvienceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvienceId");

                    b.HasIndex("Name", "PostalCode")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EntityLib.LocationManagment.Provience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Proviences");
                });

            modelBuilder.Entity("EntityLib.ProductsManagment.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CuisineId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuisineId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntityLib.RestaurantCuisineManagment.RestaurantCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantCuisines");
                });

            modelBuilder.Entity("EntityLib.RestaurantManagment.CuisineRestaurant", b =>
                {
                    b.Property<int>("CuisinesId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantsId")
                        .HasColumnType("int");

                    b.HasKey("CuisinesId", "RestaurantsId");

                    b.HasIndex(new[] { "RestaurantsId" }, "IX_CuisineRestaurant_RestaurantsId");

                    b.ToTable("CuisineRestaurant");
                });

            modelBuilder.Entity("EntityLib.RestaurantManagment.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("Banner")
                        .HasColumnType("image");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<long>("ConatctTel")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactMob")
                        .HasColumnType("bigint");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrderLedTime")
                        .HasColumnType("int");

                    b.Property<int>("PercentageCutOff")
                        .HasColumnType("int");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProvienceId")
                        .HasColumnType("int");

                    b.Property<string>("Reservation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesTax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvienceId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("EntityLib.CuisineManagment.Cuisine", b =>
                {
                    b.HasOne("EntityLib.CuisineManagment.Cuisine", "ParentCuisine")
                        .WithMany()
                        .HasForeignKey("ParentCuisineId");

                    b.Navigation("ParentCuisine");
                });

            modelBuilder.Entity("EntityLib.LocationManagment.City", b =>
                {
                    b.HasOne("EntityLib.LocationManagment.Provience", "Provience")
                        .WithMany()
                        .HasForeignKey("ProvienceId");

                    b.Navigation("Provience");
                });

            modelBuilder.Entity("EntityLib.ProductsManagment.Product", b =>
                {
                    b.HasOne("EntityLib.RestaurantCuisineManagment.RestaurantCuisine", "Cuisine")
                        .WithMany("Products")
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLib.RestaurantManagment.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId");

                    b.Navigation("Cuisine");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("EntityLib.RestaurantCuisineManagment.RestaurantCuisine", b =>
                {
                    b.HasOne("EntityLib.RestaurantManagment.Restaurant", "Restaurant")
                        .WithMany("RestaurantCuisines")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("EntityLib.RestaurantManagment.CuisineRestaurant", b =>
                {
                    b.HasOne("EntityLib.CuisineManagment.Cuisine", "Cuisines")
                        .WithMany("CuisineRestaurants")
                        .HasForeignKey("CuisinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLib.RestaurantManagment.Restaurant", "Restaurants")
                        .WithMany("CuisineRestaurants")
                        .HasForeignKey("RestaurantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuisines");

                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("EntityLib.RestaurantManagment.Restaurant", b =>
                {
                    b.HasOne("EntityLib.LocationManagment.City", "City")
                        .WithMany("Restaurants")
                        .HasForeignKey("CityId");

                    b.HasOne("EntityLib.LocationManagment.Provience", "Provience")
                        .WithMany()
                        .HasForeignKey("ProvienceId");

                    b.Navigation("City");

                    b.Navigation("Provience");
                });

            modelBuilder.Entity("EntityLib.CuisineManagment.Cuisine", b =>
                {
                    b.Navigation("CuisineRestaurants");
                });

            modelBuilder.Entity("EntityLib.LocationManagment.City", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("EntityLib.RestaurantCuisineManagment.RestaurantCuisine", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EntityLib.RestaurantManagment.Restaurant", b =>
                {
                    b.Navigation("CuisineRestaurants");

                    b.Navigation("Products");

                    b.Navigation("RestaurantCuisines");
                });
#pragma warning restore 612, 618
        }
    }
}
